stages:
  - build
  - test
  - install
  - deploy  # dummy stage to follow the template guidelines
  - review
  - dast
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup

install:
  image: maven:3.6-jdk-11
  script:
    - 'mvn deploy -s ci_settings.xml'

include:
  - template: Auto-DevOps.gitlab-ci.yml
